### ISSUE TITLE
DP5G HV value taken from status packet

### ISSUE THREAD

**Issue by hinxx** [epics-modules/mca#19]
Currenty the IOC does

https://github.com/epics-modules/mca/blob/eb635637c5c295340a2e319ae97ba08658ea9595/mcaApp/AmptekSrc/drvAmptek.cpp#L748

According to the DP5 Programmers guide B1, page 71, for DP5G the bytes 30 and 31 are N/A.
As they are now taken into the `$(P)$(R)HighVoltage`, without detector type checking being done, the reported HV value to the user seems off.
For example, setting HV to + 616 V gives an impression that HV is barely ~100 V (status value). At the same I believe that the detector actually does use + 616 V, and not ~100 V, due to `HVSE=?;` command value on readback. I would need to somehow measure the HV to be 100 % sure.
Also, vendor windows tool, DppMCA, does show correct value in its UI, but that is probably because it is ignoring the status packet bytes 30-31 for DP5G detector.

A solution would be to use the value as returned by the `HVSE=?;` command. It was observed that this `HVSE=?;` always returned the value user set with `HVSE=nnn;` previously.

**Comment by MarkRivers** [comment]
Closed via #24
