### ISSUE TITLE
$(P)PresetReal defined twice in SIS38XX.template

### ISSUE THREAD

**Issue by kmpeters** [epics-modules/mca#7]
$(P)PresetReal is defined twice in SIS38XX.template.  Once on line 60:

```
record(ao,"$(P)PresetReal") {
  field(PINI, "YES")
  field(DTYP, "asynFloat64")
  field(OUT,  "@asyn($(PORT),0)MCA_PRESET_REAL")
  field(VAL,  "0.0")
  field(PREC, "2")
}
```

And a second time on line 122:

```
record(ao,"$(P)PresetReal") {
  field(PINI, "YES")
  field(DTYP, "asynFloat64")
  field(OUT,  "@asyn($(PORT),0)MCA_PRESET_REAL")
  field(VAL,  "0")
  field(PREC, "3")
}
```

This doesn't cause any problems when the database is loaded; the second definition overrides the first.  It could, however, cause minor confusion in the future.  The only reason I noticed it is because I have a script that generates PV aliases and it generated a duplicate alias that did result in an error.

**Comment by MarkRivers** [comment]
I've removed the first record instance.  Thanks for catch this.
